### PR TITLE
update for chalk

### PR DESCRIPTION
**Pull request by ghost**
Update for pebble round, includes circular wall hit detection and necessary vector collision calculations...

### CODE REVIEW

**Comment by C-D-Lewis** [comment]
Nice job! I haven't looked at the code yet, just tested with `emu-control`, but first thing that comes to me is: to try and preserve the simplicity of the main C file, could you extract the circular math to a separate file, and include that?

**Comment by ghost** [comment]
I will change that right now.

**Comment by ghost** [comment]
@C-D-Lewis I've added a separate file for the round math.

**Comment by C-D-Lewis** [comment]
I believe a good practice is to put a `#pragma once` at the top of each `.h` file, in case it is included in any more complex way in a derived project. After that, :+1:

**Pull request merged**
